export const GameStatus = {
  INITIAL: 'INITIAL',
  STARTED: 'STARTED',
  PLAYING: 'PLAYING',
  FINISHED: 'FINISHED',
  COMPLETED: 'COMPLETED',
  REPEATED: 'REPEATED',
};

export const SquareStatus = {
  INITIAL: 'INITIAL',
  ACTIVE: 'ACTIVE',
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
};
